[package]
name = "trading_data"
version = "0.3.0"
edition = "2024"
authors = ["Valeriy Sakharov <valeratrades@gmail.com>"]
description = "Trading data collection and processing"
license = "BlueOak-1.0.0"
repository = "https://github.com/EV-invest/trading_data"
documentation = "https://docs.rs/trading_data"
readme = "../README.md"
keywords = ["trading", "finance", "market-data"]
categories = ["command-line-utilities"]

[dependencies]
clap.workspace = true
color-eyre.workspace = true
dep_dag.workspace = true
miette.workspace = true
trading_data_derivatives.workspace = true
trading_data_persistence.workspace = true
v_utils.workspace = true

[lints]
workspace = true
